- name: using amazon.aws collection
  hosts: localhost
  collections:
    - amazon.aws
  tasks:
    - name: Create S3 bucket
      amazon.aws.s3_bucket:
        name: my-unique-bucket-name-12345
        region: us-east-1

