- name: Install a package on ubuntu hosts
  hosts: ubuntu
  become: yes
  tasks:
      - name: Install htop package
        apt:
          name: htop
          state: present
        when: ansible_facts['os_family'] == 'Debian'

- name: Install a package on RedHat hosts
  hosts: redhat
  become: yes
  tasks:
      - name: Install htop package
        yum:
          name: htop
          state: present
        when: ansible_facts['os_family'] == 'RedHat'

- name: Install a package only if required
  hosts: all
  vars:
    packages:
      - name: htop
        required: true
      - name: vim
        required: false
      - name: curl
        required: true
      - name: git
        required: false
  tasks:
      - name: Install required packages
        apt:
          name: "{{ item.name }}"
          state: present
        when:
          - item.required
        loop: "{{ packages }}"
