- name: Deploy application
  hosts: webservers
  tasks:
    - name: Copy application code
      copy:
        src: /path/to/local/app/
        dest: /var/www/html/
      notify:
        - Restart Apache

  handlers:
    - name: Restart Apache
      service:
        name: apache2
        state: restarted