- name: create multiple users
  hosts: all
  vars:
    users:
      - alice
      - bob
      - charlie
  tasks:
    - name: create multiple users
      user:
        name: "{{ item }}"
        state: present
      loop: "{{ users }}"