- name: create multiple users
  hosts: localhost
  vars:
    users:
      - name: John
        uid: 1050
      - name: Andy
        uid: 1051
      - name: Michel
        uid: 1052
      - name: Lisa
        uid: 1053
      - name: Anouk
        uid: 1054
  tasks:
    - name: create a user
      user:
        name: { { item.name } }
        uid: { { item.uid } }
        state: present
        with_items: { { users } }
