#SPDX-License-Identifier: MIT-0
---
# tasks file for mysql
- name: Install pre-requisite packages
  apt:
    name: "python3-mysqldb"
    state: present

- name: Install Mysql packages
  apt:
    name: "mysql-server"
    state: present

- name: Ensure Mysql is started and enabled
  service:
    name: mysql
    state: started

- name: configure a database
  mysql_db:
    name: myapp
    state: present
